# Site settings
title: Caipyra 2016
email: your-email@domain.com
url: http://caipyra.python.org.br
description: "O Caipyra, é um encontro organizado pela comunidade Python do interior de São Paulo, para pessoas interessadas em conhecer ou se aprofundar nesta linguagem. Venham compartilhar suas experiências junto à nossa comunidade!"
skills: "O único evento de Python com Quentão e Paçoquinha!"
date: "De 25 à 28 de junho em Ribeirão Preto"
meta_author: Caipyra 2016

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: EE5A28;
  secondary: 343434 #FD6E8A
  secondary-dark: 343434 #A2122F
  background-green: 96A623
  background-green-rgb: "150, 166, 35"

# Footer settings
footer:
  copyright: Grupo de Usuários Python de Ribeirão Preto (GrUPy-RP)
  location: Local
  social:
  credits: Little Kahuna

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/grupyrp
  - title: facebook
    url: http://facebook.com/grupyrp

# Postal address (add as many lines as necessary)
address:
  - line: Anfiteatro de Bioquímica
  - line: Prédio Central da Faculdade de Medicina
  - line: Avenida do Café, 3000 – Ribeirão Preto

# Credits content
credits: Marco Rougeth

# Build settings
markdown: kramdown
permalink: pretty
